import { escapeHtml, toPersianDigits } from './escape';

/**
 * `/referral` — the caller's own invite code, and what it has earned.
 *
 * ── Why the bot is the right place for this ─────────────────────────────────
 *
 * A referral code is shared *in Telegram*. `HomeView` rendered it as text to
 * copy, and the copy was then pasted into the chat the user was already in — so
 * the bot showing it is one step shorter than the screen that used to, and the
 * ready-made `https://t.me/<bot>?start=<code>` link is the thing people actually
 * send. `ReferralService.claim` reads exactly that payload on `/start`, which is
 * the loop closing inside one application.
 *
 * The code is **not** escaped into the link. It is generated by the service from
 * a fixed alphabet, and Telegram's `start` charset (`deep-link.ts`) applies to the
 * same payload — but the *body* still escapes it, because a body is HTML and
 * the day the alphabet changes this should degrade to visible text rather than
 * to markup.
 */
export interface ReferralSummaryLine {
  code: string;
  invited: number;
  qualified: number;
  coinsEarned: number;
}

/** `FoundingService.progress()`: ranks handed out, and the cap (0 = switched off). */
export interface FoundingProgressLine {
  awarded: number;
  max: number;
}

export function formatReferral(
  summary: ReferralSummaryLine,
  botUsername: string,
  founding?: FoundingProgressLine,
): string {
  const link = `https://t.me/${botUsername}?start=${summary.code}`;

  return (
    `<b>کد معرفی شما</b>\n\n` +
    `<code>${escapeHtml(summary.code)}</code>\n\n` +
    `این پیوند را برای دوستانتان بفرستید:\n${escapeHtml(link)}\n\n` +
    `👥 دعوت‌شده: ${toPersianDigits(String(summary.invited))}\n` +
    `✅ فعال‌شده: ${toPersianDigits(String(summary.qualified))}\n` +
    `💰 سکهٔ دریافتی: ${toPersianDigits(String(summary.coinsEarned))}\n\n` +
    foundingProgressLine(founding) +
    `<i>وقتی کسی با این پیوند بیاید و در فعالیتی شرکت کند، هر دو سکه می‌گیرید.</i>`
  );
}

/**
 * «۶۱۲ از ۱۰۰۰ جای نفرات اول پر شده» (plan 18 item 9).
 *
 * The one reason to invite somebody *today* rather than next month: the places
 * run out. So it is drawn only while some are left — a switched-off campaign
 * (`max` 0) and a full one both have nothing to hurry for, and a line about
 * either would be a promise the next sign-up cannot collect.
 */
function foundingProgressLine(founding: FoundingProgressLine | undefined): string {
  if (founding === undefined || founding.max <= 0 || founding.awarded >= founding.max) return '';
  const awarded = toPersianDigits(String(founding.awarded));
  const max = toPersianDigits(String(founding.max));
  return (
    `🏅 ${awarded} از ${max} جای «${max} نفر اول» پر شده. ` +
    `دوستی که پیش از پر شدن نمایه‌اش را کامل کند، نشان همیشگی و سکه می‌گیرد.\n\n`
  );
}
