import { escapeHtml, toPersianDigits } from './escape';

/**
 * `/referral` — the caller's own invite code, and what it has earned.
 *
 * ── Why the bot is the right place for this ─────────────────────────────────
 *
 * A referral code is shared *in Telegram*. `HomeView` rendered it as text to
 * copy, and the copy was then pasted into the chat the user was already in — so
 * the bot showing it is one step shorter than the screen that used to, and the
 * ready-made `https://t.me/<bot>?start=<code>` link is the thing people actually
 * send. `ReferralService.claim` reads exactly that payload on `/start`, which is
 * the loop closing inside one application.
 *
 * The code is **not** escaped into the link. It is generated by the service from
 * a fixed alphabet, and `openAppButton`'s charset rule applies to the same
 * `?start=` payload — but the *body* still escapes it, because a body is HTML and
 * the day the alphabet changes this should degrade to visible text rather than
 * to markup.
 */
export interface ReferralSummaryLine {
  code: string;
  invited: number;
  qualified: number;
  coinsEarned: number;
}

export function formatReferral(summary: ReferralSummaryLine, botUsername: string): string {
  const link = `https://t.me/${botUsername}?start=${summary.code}`;

  return (
    `<b>کد معرفی شما</b>\n\n` +
    `<code>${escapeHtml(summary.code)}</code>\n\n` +
    `این پیوند را برای دوستانتان بفرستید:\n${escapeHtml(link)}\n\n` +
    `👥 دعوت‌شده: ${toPersianDigits(String(summary.invited))}\n` +
    `✅ فعال‌شده: ${toPersianDigits(String(summary.qualified))}\n` +
    `💰 سکهٔ دریافتی: ${toPersianDigits(String(summary.coinsEarned))}\n\n` +
    `<i>وقتی کسی با این پیوند بیاید و در فعالیتی شرکت کند، هر دو سکه می‌گیرید.</i>`
  );
}
